- hosts: frontends
  gather_facts: true
  tasks:

  - name: Smoke Test
    uri:
      url: "http://{{ item }}"
      return_content: yes
    with_items:
      - "{{ inventory_hostname }}"  
    register: webpage

  - name: debug
    debug:
      var: "{{ inventory_hostname }}"

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible' not in webpage.results[0].stdout"

