- name: Download Private key
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
    dest: "/home/{{ workstation_user }}/.ssh/"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: 0400

- name: Download Public key
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
    dest: "/home/{{ workstation_user }}/.ssh/"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: 0400

- name: Generate key files
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa
- name: Create OSP keypair
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
